project_name: "halyard"
version: 2

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: halyard
    main: ./main.go
    binary: h5d
    asmflags: "{{ .Env.GO_BUILD_ASMFLAGS }}"
    gcflags: "{{ .Env.GO_BUILD_GCFLAGS }}"
    ldflags: "{{ .Env.GO_BUILD_LDFLAGS }}"
    tags:
      - "{{ .Env.GO_BUILD_TAGS }}"
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - ppc64le
      - s390x

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  use: github-native
  disable: '{{ ne .Env.ENABLE_RELEASE_PIPELINE "true" }}'

release:
  disable: '{{ ne .Env.ENABLE_RELEASE_PIPELINE "true" }}'

